version: '3'

services:
  my-hugo-container:
    container_name: my-hugo-container
    build: .
    image: my-hugo-app:latest
    volumes:
      - .:/app
    ports:
      - "1313:1313"
    command: >
      /bin/sh -c "
      npm install &&
      npm run project-setup &&
      npm run build &&
      hugo server --bind=0.0.0.0 --port=1313 --baseURL=http://localhost:1313
      "
    environment:
      - HUGO_ENV=production
      - TINA_CLIENT_ID=${TINA_CLIENT_ID}
      - TINA_TOKEN=${TINA_TOKEN}
    #command: /bin/sh

#docker-compose up
#docker start my-hugo-container
#docker exec -it my-hugo-container /bin/sh
#docker-compose stop
#docker-compose down
#docker-compose down --volumes --rmi all
